# necessary library installation
install.packages("tidyverse")
install.packages("forcats")
install.packages("stringr")
install.packages("caTools")
install.packages("DT")
install.packages("data.table")
install.packages("pander")
install.packages("ggplot2")
install.packages("scales")
install.packages("grid")
install.packages("gridExtra")
install.packages("corrplot")
install.packages("VIM")
install.packages("knitr")
install.packages("vcd")
install.packages("caret")
install.packages("xgboost")
install.packages("MLmetrics")
install.packages("'randomForest'")
install.packages("'rpart'")
install.packages("'rpart.plot'")
install.packages("'car'")
install.packages("'e1071'")
install.packages("vcd")
install.packages("ROCR")
install.packages("pROC")
install.packages("VIM")
install.packages("glmnet")

# import necessary libraries
# data wrangling
library(tidyverse)
library(forcats)
library(stringr)
library(caTools)

# data assessment/visualizations
library(DT)
library(data.table)
library(pander)
library(ggplot2)
library(scales)
library(grid)
library(gridExtra)
library(corrplot)
library(VIM) 
library(knitr)
library(vcd)
library(caret)

# model
library(xgboost)
library(MLmetrics)
library('randomForest') 
library('rpart')
library('rpart.plot')
library('car')
library('e1071')
library(vcd)
library(ROCR)
library(pROC)
library(VIM)
library(glmnet) 